---
default_install_hook_types:
- pre-commit
- pre-merge-commit
- pre-push
- prepare-commit-msg
- commit-msg
- post-commit
- post-checkout
- post-merge
- post-rewrite

fail_fast: false

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=100]
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-xml
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: forbid-new-submodules
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6
  hooks:
  - id: check-mailmap
    name: detect if an email address needs to be added to mailmap
  - id: git-check
    name: check for conflict markers and core.whitespace errors

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.3.0
  hooks:
  - id: remove-crlf
  - id: remove-tabs
    name: tabs remover
    args: [--whitespaces-count, '2']

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.27.1
  hooks:
  - id: yamllint
    args: [--format, parsable]

- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.2
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --width, '150']

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.31.0
  hooks:
  - id: commitizen

- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 2.4.0
  hooks:
  - id: editorconfig-checker
    alias: ec

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell

- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.17.1
  hooks:
  - id: check-github-workflows

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.32.1
  hooks:
  - id: markdownlint
    args: [--config=.markdownlint.yml, scan]

- repo: https://github.com/Kr4is/cmake-format-precommit
  rev: v0.6.14
  hooks:
  - id: cmake-format
    args: [--config=.cmake-format.yml]
  - id: cmake-lint
    args: [--config=.cmake-linter.yml]
